name: Тестирование

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v4

    - name: Установить Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Установить Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: 1.8.2

    - name: Установить зависимости
      run: poetry install

    - name: Запустить тесты с покрытием
      run: poetry run pytest --cov=src --cov-report=term-missing

    - name: Отправить в Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
